# nixpacks.toml
[variables]
PUBLIC_PITCHLOAD_URL=''
PITCHLOAD_METHOD='GET'
PUBLIC_PITCHLOAD_AUTH_TOKEN=''
PITCHLOAD_OUTPUT_PATH=''

PUBLIC_POCKETBASE_URL=''
POCKETBASE_SUPERUSER=''
POCKETBASE_PASSWORD=''